services:
  postgres-db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres #database user
      POSTGRES_PASSWORD: 12345 #password for database
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/01-init.sql

  app:
    image: job-app:1.0
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres 
      DB_NAME: test 
      DB_PASS: 12345 
      DB_HOST: postgres-db 
      DB_PORT: 5432 
      DB_SSLMODE: disable
    depends_on:
      - postgres-db
          
      
volumes:
  postgres_data: